version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: db
    ports:
      - "5433:5432"
    volumes:
      [postgres-data:/var/lib/postgres/data]

volumes:
  postgres-data:
