version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USE: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 8084:80
    volumes:
      [postgres-data:/var/lib/postgres/data]

volumes:
  postgres-data:
